import SwiftUI
import MapKit
import Polyline

struct TrailAnimationView: View {
    @StateObject private var animator = TrailAnimator()

    var body: some View {
        ZStack {
            Map(position: $animator.cameraPosition) {
                MapPolyline(coordinates: animator.currentTrail)
                    .stroke(.blue, style: StrokeStyle(lineWidth: 5, lineCap: .round))
            }
            .mapStyle(.hybrid)
            .ignoresSafeArea()
            .gesture(
                MagnificationGesture()
                    .onChanged { scale in
                        animator.zoomGesture(scale: scale)
                    }
            )

//            VStack {
//                Spacer()
//                Button("▶️ Start Animation") {
//                    animator.startAnimation()
//                }
//                .padding()
//                .background(.ultraThinMaterial)
//                .clipShape(RoundedRectangle(cornerRadius: 12))
//                .padding(.bottom, 40)
//            }
        }
        .onAppear {
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.04) {
                animator.startAnimation()
            }
        }
    }
}

#Preview {
    TrailAnimationView()
}



// ------------------------------------------------------------
// MARK: - TrailAnimator
// ------------------------------------------------------------
class TrailAnimator: ObservableObject {

    @Published var cameraPosition: MapCameraPosition = .automatic
    @Published var currentTrail: [CLLocationCoordinate2D] = []

    // User zoom
    @Published var zoom: Double = 12500      // default camera distance

    let minZoom: Double = 5300               // closest allowed
    let maxZoom: Double = 50000             // farthest allowed

    // Track animation
    let allcoordinates: [CLLocationCoordinate2D]
    let coordinates: [CLLocationCoordinate2D]
    private var index = 0
    private var isAnimating = false

    // Speed
    private let stepDuration: Double = 0.04

    // encoded polyline
    let encodeddata =  #"gywbHqrj|CKFBPLDHBJDLDNFPDNHRDRHRDPBNHLNHPFPDP?VCVCXA^?b@@h@@j@Ap@Bh@Jj@Jj@Db@F`@H\X^BRAPIJOJMVKHODSAOEUESES?U@WHWFSPOLKDGLIFELIDIJG?IDQLIDIHKNSRSNWNKRMPIDIFMDMAKGCS?U@WAOGKICODMJOROVQZSXQROPIHAXHJTRLT@d@L\L\N^Ld@P^Nh@L^N^JXFRJTHVJ^HXJZNXL^L^L^NXHRHVLTNVNVPXNXNXTXVVRXVVTXTXPPXXRXRTPTLTRZRPPZTZTZRXRVPRF^JPJl@HXH`@Jf@Ll@HZJf@Jb@Ff@Hd@J\Hd@Jf@Fb@AN@N?R@VITEXGXCXCVEZE^E\C`@Gd@Gf@AVEd@Gb@E`@IZKZK^Q^U\S^Qb@W\S\S\S\O^U^S\S\SZQZQXMTKTIPOPSLSPURUTWNYLQRAl@Ej@Ol@Mp@g@BQd@Sf@Qb@QZQXUVSVSXOTKVE\C^GTILIPCPCRG\G`@Id@Id@Gh@E^BXFRHVFXDVDVAV@TAVEXGVMVMZIVKXG\G^I\G\KTSROLMRIXWZCd@Eh@Gj@Ih@Gh@M`@Q\U`@Qd@U`@U`@W^Md@O`@OZK^Q\Q\Ob@M\QZOVQRSPQJQNQJQLQLSNSNQLSJQLQRMRIFGJGL@NFNFDFHHD?LFX@LDNBPFPDP?P@PFHDLDPFLDJBPBNFNFN@T@PJLNHLNJNNHLJHFFHFNLHHJLLHLHFLFHJHJJJJNNHPRDHNJNJFJBPCLCRCRIJIJMNITMRETKXOVMXQNORWLUTUVO^O^Id@E^C^C`@E\ATELGHKFOLOPKPGRGZERDXBTBTA\MPCNILCPMJIHIPINENCLETCRCLANGXCNCLANGVCNCJEL?PATAT?VATGNCNELELCJGLGTGPINIHINGFMLGHGFIHIFI@KNKDMFMDMJMLKJOHOHOHQJQNOFSHSDULQLQLKNMRORMPOPMZM\OVQLSHSRORORQPUJUPSRMPGVGHOBOLORQTOVINKDO@MLOZQ^UHYBUNUNULWNWNQPKNMJGLEPCN@LINCNCN?P@VBZ?`@@^?b@H`@DXBXFPDTBR@P?T?XCVAXEPATEN?RAT?TEVAVCPAN@RA\@\A^?X@PAP?R@X@TBT@NDL@TBPDTDN@TDTDRDXDZDXBZDN@VCNEN?LEPFLHHHB@LDL@L?L@RBTAN?NAP?R@PBP?P?L?TBX?NBV@TBN@NBPPRLBFJDJBJGGKOIEI@CKEKGGCM?OC_@CO@QATF`@FZFTHJJBLJDPFBDRBPAZ?d@Ch@Aj@@h@Db@ATCR?V?VANEFENIRIJMLKHIHGDIDKFKFIDKBKLKFIHGFKFM@MHMHOPOVO\IVIPIZKRKNMRKRKVK`@OVOZKZG`@IXMRKNQLMFMJMPMVMLIDCV?VE^EVELCT@VCNIRGPGPGLELMDMLQPSPSLMLKRONORMJKHGPOTM\M\Id@M`@I`@I`@E^G`@K\G\GV@RALGNMHO?MBQHSHELKHIKIAKJOBKDCREPKPMJKBOBMBKAMJOBOFILMNQ?SHSDUDWBSFQ?W@QBOBK?OEOKU?W?UGWBU?WGUIOGU@S@QNWJWFWJWLSNMNKROROTQVOHOLQHQPONQFQJMNKLKFO?WBUDUFW@SJQBSHQPUNQJMDKDM@IFO?KBM?KBM?O?Q@QBQ@IJQPOJSHSNU?O?MEM?IFONSBQ@SDSDSDUDM@QAS@SCUAWEWAW?S?UGQ@GAGIQ@MDOHK?QEQ@O@UDOHMLMJKNKLMJMPIJMNMLMLG\KNOJOLQPQHQBQBSAOKSCQCOGSKSEQCUBQ@UBUBW@YDU?WHYNUPMDQHOJMLOJOJQFU@SDMDK?K@O@SBOBWDWHYBU@]DWHWHSPUVQNOJSFSDOBMDOBO@SASBOFODSBSDUNYHKESBQBSFUDQHSLMNONKHKDIDELINSLUNSLQPKHSFSLQLQFQFSFQJQJSJSFSHULSNSLOJQLQHQLOLONSNONONMPOROLKJMLQNQNQNOPKNIPGNSJMJKJKJKNKHKLKBKFIHI@MTKPIPCJELCNELELCPELGLCTEPGHEJELCLIRCJEPEPCTCRCNGJANCNITETCVGLIRCREPIRCTGLANGNKXEJEJCPCPBRDJDJ@NBJ@JFHFF@LDRHNDJHJDLFFHLHJDHDJDJBNFPDNFHFJBXFHFHFLFNHHLFFFHDFJHHHL@V?PBP?N?PCRCN@LCPGJINMHGDK@MAMCOGGUKKMKOGSISEUCU?WAUEYGWIYCWGUGOOKWIYKWKYE[GQQESESMKUG[CYC[EUAMKGEIIGIEGDGLCRAXCZC\C`@B`@D^H`@NPLZJ\NZN\J\Hb@Hb@Hb@Ld@Lj@Hb@Dj@Fj@Fj@Df@Dn@Df@?f@C\CXBXHXH\J^F^D^D\GNCNAXGt@Id@Cd@Eh@Ch@Ch@Ab@Cb@C\Mb@Id@Gh@Gj@Ej@In@Er@Q`@Kf@Sf@Qh@Oh@Gb@Eb@A`@@`@F^D`@NZN`@Db@?^C\?`@B\H^L^L\F^Bh@Dd@Fd@Jh@Nh@Tb@Jf@Fd@Db@D\DTDNHHLRFFHDHPD\BRFVHTJZJZLTFX@XBX?V?RALMLKRATCPEJ?LDHBNAN@N?VBLJDHDHFJNJLDNBNFNHVJPNLFPBTJDLFHFHNJJLJHHHLH@FDHHDFFHBL@N?R?P@T?VBPALDP?VAT@LDNDNBPBNBN@P@L@Z@L?N?P@L?LAT@T?Z@LBNBNFNFRDPFNFLBL@R@T@TBPDPFRDJFX@N@RAPCT@LBXDL@PDNBRDNFNDPDVBXFZJZHPHRDTDTFVHPFP@L@XDNFPFRFPHJHNAPL`@BRDTJTFTHTHPHRJPFPJPFXBJAKPPBTLJDPBRDHFLBNDHHPDJDNHJFJHHCPFJBPDJDHCLDKGKBJBJCKGMCKCKAMCOCMGIKIGIEKEICMGMCOIICOCKIOIQCMEMCOIIKBHADJHNDLFHFLFLHLDLDJDLDJHHBL@NDJHJHDFP?LBPDJFJ?L@L?JCKDHFEDMFKHGLGNGNMFIJIJIJGHIHEHEHIJALMFEJAL?F?RALIRCNCN?JBH@HCPONONQLOJGJGJINUJMLKNOJMPGNCRCTELORERANKJQJSLSNSPQPONULUHWDWFMBMBOPIJQDWJSHQJSJWJWNQNUNSRQRYNQRQJSFMTOJQHSLOLGLQNOLQLOLILSFQFMNKNIJOJSLQNMLKRAPGPCHAHAJCFELAHGJGNENCNALCLINKNIPGRIP?PANEPETERELCJELKHGLKNEJ@J?HKLEFCNGNCLCFWHIHQJMJMLMNQLSJMHKDIDKHOHGHIDMDQLMHSHUFWJOHMFQDMNSPQPQJOHKDKLMLKNKLKNKLOLONILOJIJILIJKHCLDTGHCHBFDHDF?HEHIFKNOFIHKFKFMJOJOJKFKDQFSHOLKDQJUHWLUNUJSLUL[LSJQLOHKBMJQJSLUJULOJMHQFYNWNWPUPWNULMFWLYJYLOFOHOHKHGDQAWBQ@M@M@M?O@U@S@SDWB[D[DYFYJSJMLUPQNSNUPWRYN[PYLWJMFQJOLMHEFAHINAHBH@PDH?F@J@J?JBL@L@N?LBNDLBN?LBL?N@L@JBJ?L?HAJAJAJ@JAL?N?LAJ?J@HAJ@FAJ?JBH?L?LBLALAL?J?JCJ?NCJ@L?N?LAP?J@PCNAJAHBJBJJBPFPDL@P@T?TAT?T?R?R@R@TBT@T@R?P@RBP@NBXBL@LBLBL@L@LDTDPFPFTFRBLBL@RFPFNFJJLHHHLJLHLDPDPDLBNBLDPDJFLBLDJHNFJDHHBGIIIFDFFFFFDDJDNDNDNDPBN@N@JBLBJBN?NBNDLFHJLFFHDLDHJHBNJHDLANBJHNFFBFHNDLDH@FDJ?LDJDFFDJFNDJFF@NDLFJFNBJFJFDHHDFFJBJBJHTDNJDLLJ?FHFDFJBLDPDJDNBJDJBJDJDHHFHDHDFJDJBL@N?L?NCJ@N@N@LDHPHN?L?H?FIFHGPGLETEJEHIPCTD`@Db@@l@El@Cl@En@Cl@?d@?b@E^?\@Z?XBT@T@VD^@^@\ATCN@R?RBX?RCTCLENEHARAL@NDPFLBLBLCRELCNANBR?LCL?N?ZAT?PAVCPANAJET@VAX?LCNCLBLFH@LBLCJCLEH?MAPEHIJENCJALCL@LCM@MCLCNAN?LFEFDF?DH@P?^GRCLEJ@XAR?PAV@LHLNJJJLBH?BHHNJL?RDHFNHLF@GEGEGEJGIDFGK@HIAJI@FJFFDHHEJFJHH@FBFJHHFFJDHHDFHFFFFJDHFJFHDHDJFJFH@NBJIEBPF??L@P@LFHFFFHFFDHHFFLFJDHKIHFFJFDHFBJDLHJFHBJHHFJFJJBHBHHJHDNBPBTGVDRDN@TFP?N@P@N@P?N?PAP@X@R@J@LBNDN@NBT?L@R?L?P?RBP@RDL@P@N@N@PDPDPFNBLARGDAN?NERCR?L?NBLDPDLCVAPELAN?NENEPCLAPAPCLCNBJDKDK@O?M?O@MAMCM@OBK@ODKBQCUIMCOBSCQBMBQBS?QMFI@K@I@ICFBGHMBI?I?IG@PDKH?HEFGH@FAHCHAHAFADLF@EPCVAN?L@PBJHN@PAPGFANCNCRCPEV@NGNAP?MBMBW?Q?SBQDKDKDKBQ?QCOEMCM?QBO?QDSASBODO@MCKCMIICKCSAM@QCOESAS?M?OAMBOAOFGBNJJHJHLJBJAJBDHCMI@GBK@KEIEGKIEGGGG?Q?MGKCOAM@MCKCQAMAQ?Q@M?SBM?MAMCKIDGHELCJOLOBOFIJGLHAKNGLGJGHGHEHGNGHCLETGJIPCLGJS@KDK@M?K?MBIHERGBCQKCKAIRGZIHI@ONGFIDEJGHGBIFHCBMFIDIFGFGHC?OIF@NKLGLGJGLKFJAAODMIDKDIEGAICBKI@I?GBK?IFKAGIGBEJBLEJCJCJIHI@?LCV@R@X?RDNBR@V@VAPAPALBJAN?R?NELGHGNEPELGNIJODMDGBMPIHIHKNONORIFKFMDKDINOLQNQHSFOFMHQFINGPGLGHGR?TAVAJCNAVCNGLCRIRERERGXCL?R@R?PHRFLJRPDJCHGJDJFHDFDFNFFFJBVALEREVCTCJCLELENELFHRLJFBLAJHLHLLJLLRHNBARDLDNBPDNFHPHLHDHHJHOBWFOHOFMLOJYLQLUNMJMNKPKLINONMNSLOLKPKHCFGHGBOCLCJKCIBMJKFMNMPQNORMNSLUNOHQTGVKRQRMTMVIVEP@P@JBLFLFHFJDJJBP?NDP@LFLJJDJHN@NBNBJFJBHHHDH@HILGNGFEHEFGHEH?H@FBLAFIHBJCFJP?HAH@LALFFJJBN?HBNNFJDHDPFTHRDHDLJBLBJKJ?HDEKKDGDCLIDEKH?PGFE@MANNBLDVAX@\@N?IEHCNAH@LALCJCLEL?LCNELILCLEL?LGNGLKJGJEJALCHIJFFDFGGDEGDFHAH@RPDLFLJNFRHTHRJPHNHDFJBJLTLHFHLJLLNLLHLHJFLDFBL@LHHBFDDJFJLLHHJ?LKBKFCHBDNFJ@Z@VHJJHRJPHNLHJJDFLJFHHPHHHJJJJJNFNJJNPHLJRFRJLJHLQLKHEFKJCJGLCHEJEJEHEH?LEHEHGHIFQFIDIDGNKJMBKA[JQFIDODUNONFF?P?HBFJDJDHFLLLVEJENELCPENCLANGL?HAPALEJENCL?HBJHFLFHJCLELEN?NDPDNFVDRHRFNHZHTHTHTFTJTJRPPNPLRNJJNJHHJHJHNHLHLHNHPBNFNNLFJJJFJCHCTONGRGROVMVM\OXKZIZMTMPGLILSFEL?HEDKJCHU@Q?LHNDLHHLRHLDHJNJNHJFFFJDNDJHRFLDLFTDJDPDLHJHNFPHLBNDLHPLRP\NXLZFVDPDR@PJRBPJJJ@L?L?NAL?P@J@JFJ@JBJNLFDPBPBR@LBL@JBLBNFLDNDL?LHPHH@PFXHJFXFZJVJLBPBR?L?PFXHVJXFRJTDVFVFVHTDPBN@NFJDJALDPDT@R@RNVNTFL@TAT@PALANBLFh@BT@ZDZJN?P@RFLDFBRDJH?FCHCH?FCN?L?HAJCL?LBJLJ?L?LALCFIFCVCJDDHDNN?PBFNPNL@LBP@NEPEJ?HDH?HFLEH?H@HDFALAHDLJJHHDJJNJJPHNFPJPFHDTFNBNFLFJFJFLFJPJJLBJ@NDLHJDNBLFPFPDRFJ@PFPFFDHBNFJDTHLHRDNDJHJFJFD@V@NFNFPJFFLLVFLDLJJFRHPFNJTJTJXLVLZHVFRHNFNJRLTJZJVHRFTPRLPJXJXJNJLTTLPJNHHFTJTBNDJFHDXJPFLJTHHFLHPDHDJHNHRFTFJDLDPDJFJDNHBBJHJBHBLFFBNDRFPFPBJ@NDRJTDJJHHVHLHNDLFLBLJJL?NET[LMNELGJIPKTO\MZO`@SXUR[NSPE\CZQLQNGHOHORINIJKNALDN?LGNEFGFKHAJI@MHKFDDLFJFFFDJHHHHJBLHNJNFFLHHFFDLAJEHAP?LFDJTPR?TDLDFH@T?N?TDVFT@XBTFTDRATBPCLGPEL?NETAR?R@PCL@V?RDJALANHN?ZAT@RI`@?T?R@RINGPEPELFJAXCP@NCXAPBNA\AN?T?PAP?^@P@P@R?VAPANAPANAR@RCLAREV?NGRGX?PKLGLALCVEX?NC\?N@P@NBVDLNPJFRBPJLGNCLBNAR@PCLCN?NBJANAJILCJBNENANAHCJ@N?LCLHHCJ?J?J@FDHDF@HBJDHBF@J@J@HALCHBHLHPHAJCDJARBNFJFLAP?P@LBJ@P?NBJHRFLBLBLLJDNDHDJFNDP@NCLCLFNDLJJJL@NCQN@FP@NFJBN?JLJBRAPALFNCJALBLFPFJBLBNBTAL@NDTBJCNAR@TDNBPHHAVCNDVDTHZCRFRJTDZHXJZFZHXFPDNLNFPHTHTNNLRNPJLLHNLLNLHHLH?JJNFFNDJDHFJJHFFFJBLNVLJHDLHJDJ@LJBPDPNLLRLLNJJLHFJHH@HKF@L?JEFINAJHHAJCJCH?LKDMJGHBH@JCNALHH@HIHGHFHBHGJEJ@FALHN@H@L?L@N?FAJ?HTP?NCDIHFLHLCJDHHHFH@NGLAJEFBDJLPJDHDLBP@RAJOFKFIFGFCH?HEJIPIJEJIFEHCHEHALCJ?H@LELAH?HCNELKHCJGFGFIHIBKJILKDIJGFCJMJEL?JAJGRAJ@H@HAJBHDLEJGJ@JGFMAQDOFIBKBOHOFILAHFH?HHN@FGLMLAJFFPFLBTBVJLBNFJJ?HFLFHBHDHDHHJDLFLDNDLFLFPFPHPAN@HFJLRDN@NENCJCNCNELGNIHMDOFQDSBUDOFUDOHQ?QBODS@O@SBUBQDMFODW@MBYBQ@WAUBWDUFUBWDSFU@YDOBOBOFO@OGSCMBSDGHIHCJAHEDY?MBMHGHIHENKHGLELCJKJEJKL?LANGLKJGLELCLKPGLGHENKPEJCFIBMFGJGHCJILGLGNELGNINETKPGPGFIJEFEJARILAP@NCLEP?NAP?PAPGRAP?RAR?TEPGNCLCJCNGJENGLKLELAJGJENCN?NHNDJ?J?LPLLT@RDPBL@P?PGRGPIJALCJ?HCRDNBPCL?L?R@THRBPCPAPGVEX?RJJLPHLHLAPKLCHNLBNBNBPBR@P?TCPIN?NDRILKNKLKJKLOJOHGFCJGHIFELOJKJQJOPSRONQH[NSNQJSLOLKH[HQBQDUDUHQJQFSFSDUBK?O@WAU@Y@YHWNUROPWJWP[P]R]LINSPQNOPIRARDVDRHVFTFXDXDVBZDTCRGRKTOLQNUNUPWPQRIXGXATGVCXCXEXEVITIVATEJKHAJBJALELAJGLMNENINKNQNSJQHMLMHSHKJOPONMPENGLCLKFILEHKJMLMNMNOLOLQJQHQDOBMDKDKDQBQFKJKFQJQFSJSFUDOFIJJ@NDR@LJFHK@OBKCL@LFBJ?HAJ@DHGBCNI?GDIAICGDGMHHI?I?FFH@FQHIHAH?JAIDIDI?GGCKAQAMDL@RIC?O@MJKDIHUDKDMDMFMDOFOFOFODMDOFKBKDKFKFWDINGDMCMBSAQ?U@WDW@O@O@QJKBOAS?OAQAO?O?M?WAWA_@A_@?c@E]Ca@W]MWE_@Ae@Cc@Ea@Ca@Ac@Ag@Dk@Le@De@Lc@Nc@Na@Na@J]Jc@Ha@H[F[F_@^MTQZMVSXO^Qb@S^Q`@U\OTSRQHYN]V[Ta@Rc@Re@Jm@Nm@Pe@Ne@Lm@Hu@Ju@L{@Pm@Pm@Po@Ro@Rm@Pi@Zc@V_@Rc@VSXOZUTQPINCLCLETEPAVAXETCZH^Bb@H\@VATETKPKPITYd@Y^_@Za@TQL[LYH[PWTUN_@D_@DYHQHa@Fc@@]BUDOJGTGDYLMNKNMRQNWLWLSNQPOPOLSNONMPMNQPOPQPWNYNYPWNWPEJ[Pc@PWTKROP[N]LMBQHG@MCMCMEOCKGQAOLOLINAH?FEDKJO@O@MBU@O?MEQOGKKKGMQGCGEKGGGMIIMMIGEOCCMGGCSGQOMIQIOESIQAYAOEQAMCSISCWAY?Y@W?[AY@Y?[@[B[?[EQCMAUEKCWCOCSAMAW@OIKGGESGUK[Ke@K]K[KWCWGUKYIYEYISIUISGYASCQAOCQEO?UBU@UBS?WGc@C]AWCUAYA_@E]?c@AWCc@C]Ce@Cc@Ka@Aa@GQASEMESCSGMEMGMFKBKIKS?GDGMGYIGMKGQEYESAWASEWAQEOGWGEMOGKEQAOOWKYESCU@UCOI[EY?S@YAS?O@W@O@U@QBUBW@WCYCWAW@QAQAMGKIQKOKUOSQSMUMOIMIKGAOGKKGKKKKCOGQMQOMUI[ISIQKEIFO?K?O?QFSJUJQHWJS@QLQJULI@SJWGUGSEQEOGGGKEKDGGMMIGEMMGQCIKKEKIGGICMCGGI?GIKKGEIGKIIIKIIGICOGGIMKGKIIOKMIIIIGIGIQMGKEIIKKGEKIKKIGGGIEGMIGEIGSIWMEEIKKIEAMEKEKIQMMGOGUIEIMEUASOIIMKQKOGQGSEMGMEQESKMEKGGEOAQEO?SAQAOQ?GAKDGBIBKDWk@QWSUQ]QWQWSQ[I[E_@AWC[@]Aa@?_@C]E[MYQ]GW@UFWLUVYJ]B]I_@Ca@E[OYOY]Y[[[_@U[OYAYD[H]Ja@J_@J]DYEYIUOSYUY[Y]Y]Q_@I]C]E[CWKQUO]Q_@Mc@QWSSOMQIOGMGKEMEMGKEKGIGICMQIKMMMOOOQSQUQSUWUWW[WYY]W[WYSWQSQSSUOSQSQQSWUSQOOMOSQWOUSWOYQ[K]MYKOIQGQGQCQEMGMGOISMUMOOQQMMGMIOGMIOGKEMGMGOGOIOIOIQIQKSKSKSMSKQKSKOIMIMGIGIEMIMEGIEFGL@LFRFTHVJXJ\J`@L`@Jb@Ld@Jf@Lf@Jh@Ld@Jb@Hd@Fb@Fd@Bd@Bd@Af@Af@Id@Kb@Kb@O^O^Q\Q^QZQ\OZOXMVMVOVKRIPEHIBEIHUWq@GQIWHFDOJIFKFSFKMG@KIKIBI?KGIAGCICIGGGICGKGMISCYCMCOEOIQIEIGGIEIGKGEKAKCMAIFKEIGGMMUOAICQAMBI@OCOGKUEWEMCMEMKMISKGIGIKGAGDK?KAMCKCMAM?IDM@KAKAKGMAIEKEM?QK[CQCMCMAOBIFGFUBOBQ@O?OFSHMHMLQDSDQDKFQBGNKHMNOJSBKDQDKDIHOBKBMFSJQN@WK?KAKAK@KAK?K@I?IDKDIFIHIHKDKFIHEFIJGFIBDJ@NBHDIBKGH@MAL?OAMGNCJALCLGJQRGJMHOFO@MHQJQHSPUJSJOD[DODOLSNQDI?IHELINSJSJSHQPSFILM@S@MCM@MHW@QFQ@W?SCSCQEM@UGSDQCUBUDQCSASASDQBO?OBSFSBQFQBIGO@M?IBOBQEO?M?IJK@KCKAGDGICJIREPINELINMPGPGPIJEJIJMHILIJIPGRGVEVGVE^A\CTET?TEXA^?ZD`@@NA\A\AXCZ@TC^C\E\A\Gd@Ed@Mb@G^B^?^AZE\G\IZGXGZI^MPIVCTAZEXI\CZCX@ZDJDL?VATDHBLFZDP@PBVAZ?VARHJDVBTEZ@PFPBNDV@TDTDRJN@NDRDL@V@TDPBR@RCR?TBV@^BX@XDTHVHP@PBLBLDNFN?TDVFPDNFJDJJLHZFTDRDRDL@NFJHFHAH?FFG?IEIDGCEKHBF@H@HDDHHABH@NHJDJ?LEKIGAMEMFEGFGDGK?QGGEJFGICI?GEIICMAOGOGQCSESGMGQMQGKCKGUESESGSKSAOASCSGUEWEY@[AYAYA[?YAU?QEQEWA_@A[EQMKEOC[CY@SKWEY?SASCUAY?SEUCWE[C[I]E_@?QCKCa@Ia@@YHYF[F[F]Hc@HWHMDU@UHUDKBWB[Bc@D_@Da@Fa@B[@a@D]@]BYF]@Y?]B[@a@Aa@Bc@B]?S?MEQ@YB]B[BYDS@WHSDU@WFYBWJWFQLIJMHOFGJMFODKFQFOHIHQDOBMHKFIFIFCEKBMPBHNCHI@IAIDBK@SAQCWAKAYAM?OCU?c@?]?Q?S@[?]?SHc@ES?ODQ?S?S?_@DYBUBUAOAQAOCQCKEMGOAOAMCKEMIKIQGSKUKSKQGUGOGOMWGIGQGOKQIUMUIKMQMKMOMWMSMSIKIIIMCOEQCMGIGMIMCOEUEQGOISKSMUKQGOIOGICOMUCOEQEKEIIUGKCSIQGSGQIQIWEUIUGSIQIOESCOCQEMCQCQAWCU@QBM@SCQ?QCKCK?Q@O?SAOCMAQGMGICKDMFILEFOFODMBSBMBOBMDKBQDKBODMFOBKBO?O@U@ODQFUDKFOFGDIFGIIQCOEMEMGMGIMKGMEIFMEM?KCM@KCI?MEIEKGGFKAICIBKCG@KHIFK@K?KDICEODSAOCSGKCMAQAQ@OBMCS?U@Y?O?SBMAUBK?W?W?_@ASAQ?M@Q?SBU@U?QDMBU@W?]AU?M?MEOAU@QBMBSAMAQBU@K@_@?S?Q?Q?S?U?U@W@U?WBUBS@Y@MBWC]@a@@c@@e@Aa@?c@Ba@@]AYA]@[A[A]C[?]BS?O@M@YBODO@SDQBUBMGRAZEP?TETEP@L?R@RAV?T@ZBXAX@V?`@?V?Z?PIDGSAMK[IIIGMCSFIDMDOAQGKCMEKCM?KAI?IGIGGGOMEKGEOWIMGMCOIMCQFU@KBQBM@S?SAQGMIWIIEKGOCMIUHWBUDWDQFW@ODO?QEUKMIKIIKICQCOCS?SDS?SDUBYFUDMDMDSHODIFKBMDQBO@M@ODU@MCS?M?SBW@MBUISEMEKGQIQIMEIGMEMEKCOEKCYASEQCSGSCQEMEOCO?OE]@S@QBQDKBKDKFMFMDQFKHQDKBQDU@a@DYD[BUBQCUGUCQGQESCSAU?U@Y?UBSFMFGRNJC@e@EO[MOCMEKEIEMEKCIGGGKDSj@GZKZMZSZQZQXOZMVKZIZEZC^EZAXCTCTCVCZGVGVGVETGVGVGXGZC\G\C^C^C`@A`@A^AZAXAZAZ?ZAZA\C\C^E\IZG\I^Ib@Kd@Kf@Mf@Ob@Of@Kb@Md@Mb@Mb@Mb@Mb@Ob@O`@O\QZOVSVULSPWNUNUNUNUNQLQLOLONKLMJKLKLKJMNKPMPMLSNOPORQTKTMTKVGRGPEJIEMCIEIEKGMGIEUMMEQEMCQEOCOCQCQ@SHSFQHOGQ?KAGAI?QAIAMAOAUp@U@UDYFQBSCWEUGWAW@UBS@S@QCIIKOMSKIQ?MLMLMLKNKHO?OGMBOFMLQFOEKIMMQAMBOFMRKTMNKJILGLEN?TCPIRKRIHIHMHOFMFOBMAMAKAGCMIGEGGEOCKEIMEO@KFKNSJI@OBIDMHKFGBGHEJIJGNIBKAGAIDGHGPGJKHKHKJILKDMDMPODMDK?QDIAICIFK?I@GFGNCJAMBLEKANIAK@KEKAAMIKGSCW?WASCQAUAW?WBW@Y?QK[CMAKCMAO?OCMEUAQESAKCMAUCSAYA[@a@Be@Da@H_@LUSr@DIBQDQDKJKHUDUAUC[GSKOKCMIMMEOEYGSGWEYCUEQIEGICOGOISG[K]Ia@I[EYG]ESIMKEGGICJBDIAMESEIMCKFMKCKOIEKDO@O@MMMEGGS?M?QDS?QCSEO?SGS@WAUEWESC[?OESMAI?GKIQIIKGMGKGIKIMMOOEIKEK@O?SCQCM?WESDMDG?PMDIFENGFELIHSPIRMPKNOJMLKHI?MFIRIFIJ?LMLGJMNMBKLILKRGVIHKBIJGTITKLKVKRGPEJIPGPMJKJMDELKBKNIBMLGFIFETELGNQAI?GBKHMFINININKLGHKJKJGDGHKHMJIHIDKHIHKHMJKJKLGJKFMBGPAREHIZCNEJCLGJILKPMRKPMPKRQPQNIJILGHGNOFGJEPGHELIJEJGPGJEJGHCLGHILGDIFGLOFO@MJKFIDOJKHGHONMFIDIDIBIFINIFKBIFGFGFKPQJMHGHGLKJMFIHIJEHIFEFGLIDEPEREPGRGPKJIHGNMTIHGDIJIDILKNKNIHGDIHGJELILMFGFMJGHKJKJIBIHGFGJKJILGDSTINILIJIJIFIHMFGLKFGJIHINKJQHGFKDIFMHEFMHELKFGDMJMRELCJAPGOIAGFGFGDGHIDANKFIHGFEJELKJKHIDGLGFIJIFCLEHENIFILINIDGDI?IFKHGFIDIDIFGHKDIDIDI@IDKHKFEJGDGHENGFGFEHIJIDO?KIMIGIKEGGKEIIGQMMGEIKIMISMUOWSSQSSUMYK_@Ga@Ia@Ec@Ea@Ea@K[M]O[Q]Q[O[K]I_@CY?YB_@@_@Ba@A_@?a@G]I]K_@K]Ma@Q_@Se@Se@Qa@Mi@Kg@Oc@O[Q[UUSUUSUSMUC_@C]Ba@Da@Fe@De@Dk@@i@Bc@B_@?[?W?S@Q?U@WB[@]B_@@c@@c@Dg@Bi@@i@Dg@@c@Bg@@_@B_@@Y?Y@W@YBY@[D[BYB_@B]Ba@Dc@De@Dg@@g@@e@?c@@e@@i@Ag@?e@B_@F]JWH]PUNYVWXUXUV]^[P]\[Vc@Tc@P]N[D_@F_@Ba@De@Be@Dc@Dc@De@De@Dc@Ha@Fc@H_@N_@L]P]RYPc@Na@Na@Jc@Fi@Bo@?s@@o@@q@@q@Bq@Bk@Di@De@L]Na@Nc@Ne@Pk@Rg@Ri@Ti@Ro@Tg@Ng@Lg@NYBi@?c@Ec@E]U[S[Q[M[K_@G_@G_@B_@F]Fa@He@N_@XWVWXSZUZSZUXY\UXSVOTORKPUL]Fe@?o@Ai@Ck@Ci@Cm@Am@Ck@Em@@k@Dg@@e@Di@Hi@Jg@Fm@Hm@Lm@Hq@Fm@Hi@Hi@Hg@He@De@Fc@Fc@Da@Fc@Hc@Fe@Fc@Fc@Fc@Bc@He@De@@g@@i@@e@Gi@Be@Je@N_@L_@Jc@R]PYRYPYR[PYRUJe@N[Hg@Lc@Hg@Ji@Fi@Hi@Dg@Fg@Hg@Dc@Fc@Fc@Da@D]D]D]D[D[HWJWJUJWJWHWJWHWFSDQDODKDKBKFODOHSFUHYJ]H[J[LYLYN[L]L]L]L]N_@Ja@L_@Na@N_@N_@N_@R[T[V[V[X]X]Z]Z]X[VYT[N[Ja@Fe@De@Bi@Dm@Bm@Do@Bq@Fs@Du@Fs@Fu@Fu@Fw@Fu@Dq@Fu@Dm@Bi@Dg@Fc@Fa@R[L_@L_@Na@L_@Nc@Ne@L_@Le@Lc@La@Na@Na@J_@Na@N_@J_@La@N_@La@L_@L_@L[Ne@L_@Ja@La@La@La@Nc@Lc@Nc@Ne@Ng@Pg@Ng@Pi@Pi@Pi@Ni@Pi@Nk@Rk@Pk@Rm@Pi@Nk@Pe@Pg@Pg@Li@Lk@Hm@Jk@Jm@Hm@Lo@Jo@Lm@Lm@Jk@Nc@Pc@Re@Pe@Tc@Rc@Te@Te@Vc@Tc@Ta@P_@P]P_@R_@P_@P_@Ra@R]Ra@P_@Ra@L]J_@F_@Bc@Ae@Ca@Ga@Ge@Ie@Gg@Ie@Cg@Ag@?a@Bc@B[FUBKDQDMDIJIFGHMLONSPUVUVWV[Z[\_@\_@\_@X[XWVWVURSNQPOLOLKHIHIFCFEHEBK?WE[M_@Oc@Oi@Sk@Oq@Ou@Mk@Gs@Cu@@w@By@By@Ds@Bo@Bk@?g@?c@A]EWGOKDELENINMRQVSRUNYJWLWDUEOKSUSMSQWQUQUUUSSOMCIAILI@_@SOYO[Q[Ya@W]M]Q_@O[QYOYSQUMWIWMYG]E[GYIYOSSQWSSSUUWSSSQSOQOMKIEEGGKKBGHIBIKEMKIMIKOIIKICKICKKEEGGIEIGIC@KOGKKKKOMGGMMGGGEIKMMIGKAQEK?KCIAKAG?M?KDQDQFODQ@S?OIKOGMU_@SYSWQSOYOYOWQOOIQCSEMMISGWGYMWQUMUIWCUAWAOCOEOEMGQAMEOEOEIGOGKGEKIIKGCGKGMCMCMAMCQASCWEUISOQOMOOOSKSIUG[CYE[K[KYKYIWGYEY?YEW?W?U@W@W?[C_@A_@Aa@B_@?[BYK]MKKOMMOEOAQCMEOGMEKEMEMEIGKMEMGIGI"#;

    init() {
        allcoordinates = decodePolyline(encodeddata)!
        
        coordinates = allcoordinates.enumerated().compactMap { index, coord in
            (index == 0 || index % 5 == 0) ? coord : nil
        }
        
    }

    // -----------------------------------
    // MARK: - Pinch Zoom Handler
    // -----------------------------------
    func zoomGesture(scale: CGFloat) {
        // convert gesture scale → zoom distance
        let delta = (1 / scale)

        zoom *= delta

        // clamp zoom
        zoom = min(maxZoom, max(minZoom, zoom))
    }

    // -----------------------------------
    // MARK: Animation
    // -----------------------------------
    func startAnimation() {
        guard !isAnimating else { return }
        isAnimating = true
        index = 0
        currentTrail = [coordinates.first!]

        animateNextPoint()
    }

    private func animateNextPoint() {
        guard index < coordinates.count else {
            isAnimating = false
            return
        }

        let coord = coordinates[index]

        currentTrail.append(coord)

        let heading = computeHeading()

        // Camera follows zoom
        if index % 10 == 0 {
            withAnimation(.linear(duration: stepDuration)) {
                cameraPosition = .camera(
                    MapCamera(
                        centerCoordinate: coord,
                        distance: zoom,     // ← ← ← uses live zoom
                        heading: heading,
                        pitch: 70
                    )
                )
            }
        }

        index += 1

        DispatchQueue.main.asyncAfter(deadline: .now() + stepDuration) {
            self.animateNextPoint()
        }
    }

    private func computeHeading() -> CLLocationDirection {
        if index >= coordinates.count - 1 { return 0 }
        return bearing(from: coordinates[index], to: coordinates[index + 1])
    }

    private func bearing(from: CLLocationCoordinate2D, to: CLLocationCoordinate2D) -> CLLocationDirection {
        let lat1 = from.latitude * .pi / 180
        let lon1 = from.longitude * .pi / 180
        let lat2 = to.latitude * .pi / 180
        let lon2 = to.longitude * .pi / 180
        let dLon = lon2 - lon1

        let y = sin(dLon) * cos(lat2)
        let x = cos(lat1) * sin(lat2) - sin(lat1) * cos(lat2) * cos(dLon)

        let heading = atan2(y, x)
        return heading * 180 / .pi
    }
}
